package org.fbi.fshd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.fshd.repository.model.FsHdPaymentInfo;
import org.fbi.fshd.repository.model.FsHdPaymentInfoExample;

public interface FsHdPaymentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int countByExample(FsHdPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int deleteByExample(FsHdPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int insert(FsHdPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int insertSelective(FsHdPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    List<FsHdPaymentInfo> selectByExample(FsHdPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    FsHdPaymentInfo selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int updateByExampleSelective(@Param("record") FsHdPaymentInfo record, @Param("example") FsHdPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int updateByExample(@Param("record") FsHdPaymentInfo record, @Param("example") FsHdPaymentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int updateByPrimaryKeySelective(FsHdPaymentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_INFO
     *
     * @mbggenerated Wed Jan 22 09:39:38 CST 2014
     */
    int updateByPrimaryKey(FsHdPaymentInfo record);
}