package org.fbi.fshd.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.fshd.repository.model.FsHdPaymentItem;
import org.fbi.fshd.repository.model.FsHdPaymentItemExample;

public interface FsHdPaymentItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int countByExample(FsHdPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int deleteByExample(FsHdPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int insert(FsHdPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int insertSelective(FsHdPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    List<FsHdPaymentItem> selectByExample(FsHdPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    FsHdPaymentItem selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int updateByExampleSelective(@Param("record") FsHdPaymentItem record, @Param("example") FsHdPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int updateByExample(@Param("record") FsHdPaymentItem record, @Param("example") FsHdPaymentItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int updateByPrimaryKeySelective(FsHdPaymentItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.FS_HD_PAYMENT_ITEM
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    int updateByPrimaryKey(FsHdPaymentItem record);
}