package org.fbi.fshd.repository.model;

import java.math.BigDecimal;

public class FsHdPaymentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.PKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.FIS_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String fisCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.FIS_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String fisActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.BRANCH_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.TLR_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String tlrId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.FIS_BIZ_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String fisBizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.BILL_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.INST_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String instCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.INST_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String instName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.PAYER_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String payerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.NOTIFY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String notifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.LATEST_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String latestDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String verifyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.PAYER_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String payerActno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.PAYER_BANK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String payerBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.VOUCHER_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String voucherType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.BILL_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.CONTRACT_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_RATIO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String overdueRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private BigDecimal overdueAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OUT_MODE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String outModeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.PAY_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private BigDecimal payAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String canceldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String hostBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String hostChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String fbBookFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String fbChkFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String archiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operInitBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operInitTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operInitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operInitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operInitHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operPayBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operPayTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operPayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operPayTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operPayHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operCancelBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operCancelTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operCancelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operCancelTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operCancelHostsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operArchiveBankid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operArchiveTlrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operArchiveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String operArchiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String hostAckFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String lnkBillStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIS.FS_HD_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    private String manualFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.PKID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.PKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.PKID
     *
     * @param pkid the value for FIS.FS_HD_PAYMENT_INFO.PKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_CODE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.FIS_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getFisCode() {
        return fisCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_CODE
     *
     * @param fisCode the value for FIS.FS_HD_PAYMENT_INFO.FIS_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setFisCode(String fisCode) {
        this.fisCode = fisCode == null ? null : fisCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_ACTNO
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.FIS_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getFisActno() {
        return fisActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_ACTNO
     *
     * @param fisActno the value for FIS.FS_HD_PAYMENT_INFO.FIS_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setFisActno(String fisActno) {
        this.fisActno = fisActno == null ? null : fisActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.BRANCH_ID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.BRANCH_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.BRANCH_ID
     *
     * @param branchId the value for FIS.FS_HD_PAYMENT_INFO.BRANCH_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setBranchId(String branchId) {
        this.branchId = branchId == null ? null : branchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.TLR_ID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.TLR_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getTlrId() {
        return tlrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.TLR_ID
     *
     * @param tlrId the value for FIS.FS_HD_PAYMENT_INFO.TLR_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setTlrId(String tlrId) {
        this.tlrId = tlrId == null ? null : tlrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_BIZ_ID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.FIS_BIZ_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getFisBizId() {
        return fisBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.FIS_BIZ_ID
     *
     * @param fisBizId the value for FIS.FS_HD_PAYMENT_INFO.FIS_BIZ_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setFisBizId(String fisBizId) {
        this.fisBizId = fisBizId == null ? null : fisBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.BILL_ID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.BILL_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.BILL_ID
     *
     * @param billId the value for FIS.FS_HD_PAYMENT_INFO.BILL_ID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.INST_CODE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.INST_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getInstCode() {
        return instCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.INST_CODE
     *
     * @param instCode the value for FIS.FS_HD_PAYMENT_INFO.INST_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setInstCode(String instCode) {
        this.instCode = instCode == null ? null : instCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.INST_NAME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.INST_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getInstName() {
        return instName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.INST_NAME
     *
     * @param instName the value for FIS.FS_HD_PAYMENT_INFO.INST_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setInstName(String instName) {
        this.instName = instName == null ? null : instName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_NAME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.PAYER_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_NAME
     *
     * @param payerName the value for FIS.FS_HD_PAYMENT_INFO.PAYER_NAME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setPayerName(String payerName) {
        this.payerName = payerName == null ? null : payerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.NOTIFY_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.NOTIFY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getNotifyDate() {
        return notifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.NOTIFY_DATE
     *
     * @param notifyDate the value for FIS.FS_HD_PAYMENT_INFO.NOTIFY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setNotifyDate(String notifyDate) {
        this.notifyDate = notifyDate == null ? null : notifyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.LATEST_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.LATEST_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getLatestDate() {
        return latestDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.LATEST_DATE
     *
     * @param latestDate the value for FIS.FS_HD_PAYMENT_INFO.LATEST_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setLatestDate(String latestDate) {
        this.latestDate = latestDate == null ? null : latestDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.VERIFY_NO
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getVerifyNo() {
        return verifyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.VERIFY_NO
     *
     * @param verifyNo the value for FIS.FS_HD_PAYMENT_INFO.VERIFY_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setVerifyNo(String verifyNo) {
        this.verifyNo = verifyNo == null ? null : verifyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_ACTNO
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.PAYER_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getPayerActno() {
        return payerActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_ACTNO
     *
     * @param payerActno the value for FIS.FS_HD_PAYMENT_INFO.PAYER_ACTNO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setPayerActno(String payerActno) {
        this.payerActno = payerActno == null ? null : payerActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_BANK
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.PAYER_BANK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getPayerBank() {
        return payerBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.PAYER_BANK
     *
     * @param payerBank the value for FIS.FS_HD_PAYMENT_INFO.PAYER_BANK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setPayerBank(String payerBank) {
        this.payerBank = payerBank == null ? null : payerBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.REMARK
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.REMARK
     *
     * @param remark the value for FIS.FS_HD_PAYMENT_INFO.REMARK
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.VOUCHER_TYPE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.VOUCHER_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getVoucherType() {
        return voucherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.VOUCHER_TYPE
     *
     * @param voucherType the value for FIS.FS_HD_PAYMENT_INFO.VOUCHER_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setVoucherType(String voucherType) {
        this.voucherType = voucherType == null ? null : voucherType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.BILL_TYPE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.BILL_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.BILL_TYPE
     *
     * @param billType the value for FIS.FS_HD_PAYMENT_INFO.BILL_TYPE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setBillType(String billType) {
        this.billType = billType == null ? null : billType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.CONTRACT_NO
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.CONTRACT_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.CONTRACT_NO
     *
     * @param contractNo the value for FIS.FS_HD_PAYMENT_INFO.CONTRACT_NO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_RATIO
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OVERDUE_RATIO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOverdueRatio() {
        return overdueRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_RATIO
     *
     * @param overdueRatio the value for FIS.FS_HD_PAYMENT_INFO.OVERDUE_RATIO
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOverdueRatio(String overdueRatio) {
        this.overdueRatio = overdueRatio == null ? null : overdueRatio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_AMT
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OVERDUE_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public BigDecimal getOverdueAmt() {
        return overdueAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OVERDUE_AMT
     *
     * @param overdueAmt the value for FIS.FS_HD_PAYMENT_INFO.OVERDUE_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOverdueAmt(BigDecimal overdueAmt) {
        this.overdueAmt = overdueAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OUT_MODE_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OUT_MODE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOutModeFlag() {
        return outModeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OUT_MODE_FLAG
     *
     * @param outModeFlag the value for FIS.FS_HD_PAYMENT_INFO.OUT_MODE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOutModeFlag(String outModeFlag) {
        this.outModeFlag = outModeFlag == null ? null : outModeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.PAY_AMT
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.PAY_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public BigDecimal getPayAmt() {
        return payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.PAY_AMT
     *
     * @param payAmt the value for FIS.FS_HD_PAYMENT_INFO.PAY_AMT
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setPayAmt(BigDecimal payAmt) {
        this.payAmt = payAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.CANCELDATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getCanceldate() {
        return canceldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.CANCELDATE
     *
     * @param canceldate the value for FIS.FS_HD_PAYMENT_INFO.CANCELDATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setCanceldate(String canceldate) {
        this.canceldate = canceldate == null ? null : canceldate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getHostBookFlag() {
        return hostBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @param hostBookFlag the value for FIS.FS_HD_PAYMENT_INFO.HOST_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setHostBookFlag(String hostBookFlag) {
        this.hostBookFlag = hostBookFlag == null ? null : hostBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getHostChkFlag() {
        return hostChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @param hostChkFlag the value for FIS.FS_HD_PAYMENT_INFO.HOST_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setHostChkFlag(String hostChkFlag) {
        this.hostChkFlag = hostChkFlag == null ? null : hostChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getFbBookFlag() {
        return fbBookFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @param fbBookFlag the value for FIS.FS_HD_PAYMENT_INFO.FB_BOOK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setFbBookFlag(String fbBookFlag) {
        this.fbBookFlag = fbBookFlag == null ? null : fbBookFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getFbChkFlag() {
        return fbChkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @param fbChkFlag the value for FIS.FS_HD_PAYMENT_INFO.FB_CHK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setFbChkFlag(String fbChkFlag) {
        this.fbChkFlag = fbChkFlag == null ? null : fbChkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getArchiveFlag() {
        return archiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @param archiveFlag the value for FIS.FS_HD_PAYMENT_INFO.ARCHIVE_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setArchiveFlag(String archiveFlag) {
        this.archiveFlag = archiveFlag == null ? null : archiveFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperInitBankid() {
        return operInitBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @param operInitBankid the value for FIS.FS_HD_PAYMENT_INFO.OPER_INIT_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperInitBankid(String operInitBankid) {
        this.operInitBankid = operInitBankid == null ? null : operInitBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperInitTlrid() {
        return operInitTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @param operInitTlrid the value for FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperInitTlrid(String operInitTlrid) {
        this.operInitTlrid = operInitTlrid == null ? null : operInitTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperInitDate() {
        return operInitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @param operInitDate the value for FIS.FS_HD_PAYMENT_INFO.OPER_INIT_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperInitDate(String operInitDate) {
        this.operInitDate = operInitDate == null ? null : operInitDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperInitTime() {
        return operInitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @param operInitTime the value for FIS.FS_HD_PAYMENT_INFO.OPER_INIT_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperInitTime(String operInitTime) {
        this.operInitTime = operInitTime == null ? null : operInitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperInitHostsn() {
        return operInitHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @param operInitHostsn the value for FIS.FS_HD_PAYMENT_INFO.OPER_INIT_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperInitHostsn(String operInitHostsn) {
        this.operInitHostsn = operInitHostsn == null ? null : operInitHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperPayBankid() {
        return operPayBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @param operPayBankid the value for FIS.FS_HD_PAYMENT_INFO.OPER_PAY_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperPayBankid(String operPayBankid) {
        this.operPayBankid = operPayBankid == null ? null : operPayBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperPayTlrid() {
        return operPayTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @param operPayTlrid the value for FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperPayTlrid(String operPayTlrid) {
        this.operPayTlrid = operPayTlrid == null ? null : operPayTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperPayDate() {
        return operPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @param operPayDate the value for FIS.FS_HD_PAYMENT_INFO.OPER_PAY_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperPayDate(String operPayDate) {
        this.operPayDate = operPayDate == null ? null : operPayDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperPayTime() {
        return operPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @param operPayTime the value for FIS.FS_HD_PAYMENT_INFO.OPER_PAY_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperPayTime(String operPayTime) {
        this.operPayTime = operPayTime == null ? null : operPayTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperPayHostsn() {
        return operPayHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @param operPayHostsn the value for FIS.FS_HD_PAYMENT_INFO.OPER_PAY_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperPayHostsn(String operPayHostsn) {
        this.operPayHostsn = operPayHostsn == null ? null : operPayHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperCancelBankid() {
        return operCancelBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @param operCancelBankid the value for FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperCancelBankid(String operCancelBankid) {
        this.operCancelBankid = operCancelBankid == null ? null : operCancelBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperCancelTlrid() {
        return operCancelTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @param operCancelTlrid the value for FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperCancelTlrid(String operCancelTlrid) {
        this.operCancelTlrid = operCancelTlrid == null ? null : operCancelTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperCancelDate() {
        return operCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @param operCancelDate the value for FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperCancelDate(String operCancelDate) {
        this.operCancelDate = operCancelDate == null ? null : operCancelDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperCancelTime() {
        return operCancelTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @param operCancelTime the value for FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperCancelTime(String operCancelTime) {
        this.operCancelTime = operCancelTime == null ? null : operCancelTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperCancelHostsn() {
        return operCancelHostsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @param operCancelHostsn the value for FIS.FS_HD_PAYMENT_INFO.OPER_CANCEL_HOSTSN
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperCancelHostsn(String operCancelHostsn) {
        this.operCancelHostsn = operCancelHostsn == null ? null : operCancelHostsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperArchiveBankid() {
        return operArchiveBankid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @param operArchiveBankid the value for FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_BANKID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperArchiveBankid(String operArchiveBankid) {
        this.operArchiveBankid = operArchiveBankid == null ? null : operArchiveBankid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperArchiveTlrid() {
        return operArchiveTlrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @param operArchiveTlrid the value for FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TLRID
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperArchiveTlrid(String operArchiveTlrid) {
        this.operArchiveTlrid = operArchiveTlrid == null ? null : operArchiveTlrid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperArchiveDate() {
        return operArchiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @param operArchiveDate the value for FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_DATE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperArchiveDate(String operArchiveDate) {
        this.operArchiveDate = operArchiveDate == null ? null : operArchiveDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getOperArchiveTime() {
        return operArchiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @param operArchiveTime the value for FIS.FS_HD_PAYMENT_INFO.OPER_ARCHIVE_TIME
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setOperArchiveTime(String operArchiveTime) {
        this.operArchiveTime = operArchiveTime == null ? null : operArchiveTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.AREA_CODE
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.AREA_CODE
     *
     * @param areaCode the value for FIS.FS_HD_PAYMENT_INFO.AREA_CODE
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getHostAckFlag() {
        return hostAckFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @param hostAckFlag the value for FIS.FS_HD_PAYMENT_INFO.HOST_ACK_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setHostAckFlag(String hostAckFlag) {
        this.hostAckFlag = hostAckFlag == null ? null : hostAckFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getLnkBillStatus() {
        return lnkBillStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @param lnkBillStatus the value for FIS.FS_HD_PAYMENT_INFO.LNK_BILL_STATUS
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setLnkBillStatus(String lnkBillStatus) {
        this.lnkBillStatus = lnkBillStatus == null ? null : lnkBillStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIS.FS_HD_PAYMENT_INFO.MANUAL_FLAG
     *
     * @return the value of FIS.FS_HD_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public String getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIS.FS_HD_PAYMENT_INFO.MANUAL_FLAG
     *
     * @param manualFlag the value for FIS.FS_HD_PAYMENT_INFO.MANUAL_FLAG
     *
     * @mbggenerated Thu Jan 16 16:58:30 CST 2014
     */
    public void setManualFlag(String manualFlag) {
        this.manualFlag = manualFlag == null ? null : manualFlag.trim();
    }
}